# Makefile template
PROJ_ROOT = ../..

include $(PROJ_ROOT)/IncludePre.mk

LIB_NAME = ftom_command
LIB_SRCS = $(wildcard *.cpp) $(wildcard */*.cpp)

TARGET_NAME = 
TARGET_SRCS = 

LIBS += -lpthread -lftom -lftgm -ljson -lnetsnmp  /home/xtra/KompexSQLiteWrapper-Source_1.11.13/lib/debug/KompexSQLiteWrapper_Static_d.a -ldl

include $(PROJ_ROOT)/IncludePost.mk
