# Makefile template
PROJ_ROOT = ..

include $(PROJ_ROOT)/IncludePre2.mk

LIB_NAME = 

LIB_SRCS = 

TARGET_SRCS = $(wildcard *.cpp) 

LIBS += -lpthread -lcommand -lftgm -ljson -lnetsnmp  /home/xtra/KompexSQLiteWrapper-Source_1.11.13/lib/debug/KompexSQLiteWrapper_Static_d.a -ldl

include $(PROJ_ROOT)/IncludePost2.mk
